"""Create all base tables

Revision ID: 340e952d67cc
Revises: 
Create Date: 2026-03-12 08:05:44.927949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340e952d67cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_master',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('organization_name_raw', sa.String(length=300), nullable=True),
    sa.Column('organization_name_normalized', sa.String(length=300), nullable=True),
    sa.Column('address_line_1', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=5), nullable=True),
    sa.Column('organization_type', sa.String(length=30), nullable=True),
    sa.Column('solo_practice_flag', sa.Boolean(), nullable=True),
    sa.Column('large_system_flag', sa.Boolean(), nullable=True),
    sa.Column('practice_size_estimate', sa.SmallInteger(), nullable=True),
    sa.Column('name_change_count', sa.SmallInteger(), nullable=True),
    sa.Column('first_seen_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('physician',
    sa.Column('npi', sa.String(length=10), nullable=False),
    sa.Column('entity_type', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('npi_deactivation_date', sa.Date(), nullable=True),
    sa.Column('npi_enumeration_date', sa.Date(), nullable=True),
    sa.Column('first_name_raw', sa.String(length=100), nullable=True),
    sa.Column('middle_name_raw', sa.String(length=100), nullable=True),
    sa.Column('last_name_raw', sa.String(length=100), nullable=True),
    sa.Column('credential_raw', sa.String(length=50), nullable=True),
    sa.Column('first_name_clean', sa.String(length=100), nullable=True),
    sa.Column('last_name_clean', sa.String(length=100), nullable=True),
    sa.Column('full_name_display', sa.String(length=250), nullable=True),
    sa.Column('email_pattern_name', sa.String(length=200), nullable=True),
    sa.Column('credential_normalized', sa.String(length=10), nullable=True),
    sa.Column('name_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('primary_taxonomy_code', sa.String(length=20), nullable=True),
    sa.Column('specialty_name', sa.String(length=150), nullable=True),
    sa.Column('derived_specialty_category', sa.String(length=100), nullable=True),
    sa.Column('specialty_inferred', sa.Boolean(), nullable=True),
    sa.Column('specialty_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('graduation_year', sa.SmallInteger(), nullable=True),
    sa.Column('years_of_experience', sa.SmallInteger(), nullable=True),
    sa.Column('experience_bucket', sa.String(length=20), nullable=True),
    sa.Column('experience_source', sa.String(length=30), nullable=True),
    sa.Column('experience_quality_flag', sa.String(length=20), nullable=True),
    sa.Column('graduation_year_last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gender_raw', sa.String(length=1), nullable=True),
    sa.Column('gender_normalized', sa.String(length=10), nullable=True),
    sa.Column('gender_source', sa.String(length=20), nullable=True),
    sa.Column('gender_confidence', sa.String(length=10), nullable=True),
    sa.Column('gender_last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retirement_risk_flag', sa.Boolean(), nullable=True),
    sa.Column('growth_profile_flag', sa.Boolean(), nullable=True),
    sa.Column('expansion_profile_flag', sa.Boolean(), nullable=True),
    sa.Column('multi_state_flag', sa.Boolean(), nullable=True),
    sa.Column('license_count', sa.SmallInteger(), nullable=True),
    sa.Column('last_call_outcome', sa.String(length=30), nullable=True),
    sa.Column('call_attempt_count', sa.SmallInteger(), nullable=True),
    sa.Column('last_called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_adjustment_from_calls', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('lead_score_current', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('lead_score_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score_decay_applied', sa.Boolean(), nullable=True),
    sa.Column('lead_tier', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_nppes_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_version', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('npi')
    )
    op.create_table('field_value_history',
    sa.Column('history_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=50), nullable=False),
    sa.Column('npi', sa.String(length=10), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=True),
    sa.Column('collected_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_validated_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['npi'], ['physician.npi'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_table('license',
    sa.Column('license_id', sa.UUID(), nullable=False),
    sa.Column('npi', sa.String(length=10), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('license_state', sa.String(length=2), nullable=True),
    sa.Column('linked_taxonomy_code', sa.String(length=20), nullable=True),
    sa.Column('is_primary_license', sa.Boolean(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('format_valid', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('last_seen_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['npi'], ['physician.npi'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('license_id')
    )
    op.create_table('physician_organization_link',
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('npi', sa.String(length=10), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.String(length=30), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('org_phone_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['npi'], ['physician.npi'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization_master.organization_id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_table('physician_practice_locations',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('npi', sa.String(length=10), nullable=False),
    sa.Column('address_line_1', sa.String(length=200), nullable=True),
    sa.Column('address_line_2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=5), nullable=True),
    sa.Column('zip_plus4', sa.String(length=4), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_primary_location', sa.Boolean(), nullable=True),
    sa.Column('is_mailing_address', sa.Boolean(), nullable=True),
    sa.Column('location_type', sa.String(length=30), nullable=True),
    sa.Column('practice_cluster_id', sa.UUID(), nullable=True),
    sa.Column('address_confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('address_change_count', sa.SmallInteger(), nullable=True),
    sa.Column('address_stability_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('address_last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address_last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usps_validated', sa.Boolean(), nullable=True),
    sa.Column('usps_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['npi'], ['physician.npi'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('physician_practice_locations')
    op.drop_table('physician_organization_link')
    op.drop_table('license')
    op.drop_table('field_value_history')
    op.drop_table('physician')
    op.drop_table('organization_master')
    # ### end Alembic commands ###
